### ISSUE TITLE
Error 1013 returned when running client as executable

### ISSUE THREAD

**Issue by russellgsystems** [LabVIEW-Open-Source/LV-MQTT-Broker#152]
@francois-normandin 

I am using the newest release and it works in the development environment. But when I try to run the process.vi as an executable I get Error 1013 see screenshot below:

![image](https://user-images.githubusercontent.com/68344965/93090882-01c36800-f663-11ea-9b44-f942a3c3fc96.png)

To reproduce the problem try to run the process.exe in the build folder below:

[Error EXE.zip](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/5218651/Error.EXE.zip)

Thank you again for your help,

Russell

**Comment by francois-normandin** [comment]
Thanks for the test harness. I'll take a look at this.
In the meantime, is it possible to specifically include this process.vi file into your buttons spec? That might be a workaround.

Usually, asynchronous VIs that are not called otherwise are excluded from the build unless we add a front panel reference to this vi, to force the builder into believing it will be needed.

To experiment quickly with that, just open that process VI and create a reference to one of its terminals. Leave that reference unwired, on its block diagram, and it will be loaded in memory by the exe...

**Comment by francois-normandin** [comment]
I usually add this snippet on the front panel of my processes, whenever they are called asynchronously through a dynamic dispatch VI. The parent process gets added, but all the child processes are not added unless there is an implicit inclusion in the build spec, or I put this snippet...

![image](https://user-images.githubusercontent.com/11728548/93092434-6a174700-f66d-11ea-9669-c1708531ce9a.png)

**Comment by russellgsystems** [comment]
@francois-normandin Thanks for your quick help.  I put a reference down in the Server process VI, but I am getting the same error. The strange thing is that executable worked prior to the version 1.0.4.

![image](https://user-images.githubusercontent.com/68344965/93094394-79939180-f667-11ea-9792-3f56c3bf2a15.png)

**Comment by russellgsystems** [comment]
@francois-normandin I discovered that the Process.vi is located on disk in the Server Class but it is located in the MQTT_Base class which I think is causing a linking issue. Could be that you moved it location in the class, but not the physical location?  If I add enable debugging then the problem goes away.
![image](https://user-images.githubusercontent.com/68344965/93156474-da55b500-f6cd-11ea-81a8-581f7deeea65.png)

**Comment by francois-normandin** [comment]
Hi @russellgsystems , 

Good catch for the process.vi location on disk, it shoudl be in the base class folder, but this was not the issue. I'll nonetheless move it to its rightful place.

I think the reference you added has fixed the issue, only to reveal that the next process launched (Session process) has the same problem. You've seen the same error code but I bet the source VI was from a different path. After fixing Session.lvclass:process.vi, you would also see the problem with the Subscription.lvclass:process.vi. It's such a nice layered cakde :-)

Now, down to the core, the problem seems to occur only with the Run VI... probably because it is not using a strict typedef.

This causes a problem which is solved by adding the reference to the front panel:
![image](https://user-images.githubusercontent.com/11728548/93206091-dd30c400-f726-11ea-9d87-ce942880a12c.png)

While this doesn't: 
![image](https://user-images.githubusercontent.com/11728548/93206153-f6397500-f726-11ea-9114-d54455c3f29c.png)

However, the second snippet was the source of very bad clone management that created a huge lag. The first snippet is absolutely stable in execution time, very periodic with a fast termination time (onStop). The second snippet was exponentailly problematic, both for launching and disposing of references. I might have been using it wrong, I did not dwell too much on why, but the RunVI is well suited to the task at hand, so I kept this pattern. The other is disabled for future investigation.

That means that the problem is solved with adding the references on the block diagram of all the processes: 
- connectionHandler process (for server EXEs)
- MQTT base process
- Session process
- Subscription process

I'll fix it in the next build. For now, you can implement the workaround in the above-mentioned processes and the EXE runs fine.

**Comment by francois-normandin** [comment]
Fixed and released (1.0.5)
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/releases/tag/1.0.5

(by the way, I'm waiting fot Websocket support before I release on VIPM Community...)

**Comment by russellgsystems** [comment]
@francois-normandin thank you for the quick release. I just tested it and it works great.  I am wondering if this blog explains the bad clone management issue you mentioned above:
https://labviewcoder.com/2016/07/06/quick-tip-asynchronously-launching-vis-the-right-way/

**Comment by francois-normandin** [comment]
Ah yes... I've read this article before! Thanks for pointing it out, that's the trick.
@russellgsystems
