### ISSUE TITLE
Implement TLS

### ISSUE THREAD

**Issue by hildogjr** [LabVIEW-Open-Source/LV-MQTT-Broker#154]
I was just looking for a MQTT implementation for LabVIEW 2019 and found this repository.

I just start to study this project and checked on https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/153 that it doesn't have the TLS/websocket implementation yet.

I opened this issue to track the development.

**Comment by francois-normandin** [comment]
@hildogjr 
Thanks for caring about this feature. Indeed it is not implemented yet. I've been mostly working on the basics last year and haven't had much time to push this project further for a while. I don't intend to use any non-LabVIEW code for this project, and since its code base is in LV2013, my intent is still to expose a connection override which can be used to create addons that add SSL support. Going native with LabVIEW's new TLS palette in LV2020 is one way to do it (see this recent [post](https://lavag.org/topic/21615-azure-iot-mqtt/?do=findComment&comment=133442) on LAVAG, for example). There are other projects that use .NET implementations, but as this is a pure LabVIEW project, again, this would be best for a addon implementation.

Websockets is absolutely on the list of things that I'd like to add, before even going to implement QoS, Will messages, retained sessions, etc.

**Comment by francois-normandin** [comment]
@hildogjr You'll be pleased to see that it will now be possible to implement TLS by extending the MQTT Connection class with LV2020 TLS-supported TCP or the TLS-supported Websockets extension from this [project](https://github.com/MediaMongrels-Ltd/LabVIEW-Secure-WebSockets-Addon).

See here for details: 
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/issues/153#issuecomment-712319246

**Comment by hildogjr** [comment]
Thanks @francois-normandin. I am just started to understand the library, with the requirements installed was able to run even the UnitTests.

My intention is run your library into an embedded NI-compactRIO system. I keep you on track.

**Comment by francois-normandin** [comment]
@hildogjr 

I have a proof of concept that works with self-signed certificates using an extension of the TCP Connection for TLS 1.2.
A localhost server + 2 clients

I just released a new package on the VIPM COmmunity repository:
https://github.com/LabVIEW-Open-Source/MQTT-Connection-SecuredTCP

This is a screenshot of a pub-sub application using the MQTT Server and MQTT Client classes, configured with this project's Secured TCP Connection.

![image](https://user-images.githubusercontent.com/11728548/96912930-056fb900-1471-11eb-9809-38a05ee9a24a.png)

I've started creating a convenient tool for creating self-signed certificates and private keys for servers (will deploy a bunch on sbRIOs soon, so I thought that would come in handy in the long run)
https://github.com/LabVIEW-Open-Source/LabVIEW-Certification-Authority

**Comment by francois-normandin** [comment]
@hildogjr If you get it running on compactRIO before I do, please report! I'm eager to see if it works on a RT target!

**Comment by jkoplo** [comment]
I too need to run on a cRIO at some point after my proof of concept. I'll be needing to do mutual auth, so I'll probably create a new connection class based on the TLS connection you already have. I've already proven out mutual auth in my other project against the test.mosquitto.org server. Should be a quick add when I get to it.

**Comment by francois-normandin** [comment]
Closing the loop on this thread with some documentation.

The mutual authentication (client certificates) is supported since version 3.2.0 of MQTT Secured Connection package.
Details of contribution are [found here](https://github.com/LabVIEW-Open-Source/MQTT-Connection-SecuredTCP/issues/1#issuecomment-1101019753).
Package is available on VIPM.
