### ISSUE TITLE
Load Class Error in Built Executable

### ISSUE THREAD

**Issue by russellgsystems** [LabVIEW-Open-Source/LV-MQTT-Broker#160]
@francois-normandin I am seeing a strange error I didn't see previously when building the MQTT library into an executable. I can build the executable but when I try to run it I get a couple load errors from some of the cases. See the attached PDF for the errors. I tried to create a simple VI to reproduce the issue, but I couldn't. It only happens in my application, which unfortunately I can't share on the forums.  I tried to add your LabVIEW Open Source Folder to the build specifications as always include but it didn't fix the problem. I looked at your drop in examples and made sure I am using the same VIs as you were in that example. Any help you could provide would be appreciated because I am stuck at the moment and can't move forward on my deployment to my customer.
[Load Class Error.pdf](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/5642463/Load.Class.Error.pdf)

**Comment by francois-normandin** [comment]
@russellgsystems I have it compiled in an exe (LV2019 SP1) without issues. I didn't have to include any folder. I'm using it right now in production with a broker (websockets) and one client per module (I have nine of them).

The type of error you have at runtime happened to me a lot with actor framework in LabVIEW 2013, and I have never succeeded in having a reproducible outcome. Frustrating. The only way I'd get the executable to compile was to put my VIs in debug mode (with block diagram), and even then I got the same failures you show with a "IDE required" to fix the errors. For some very unsatisfying reason, is get a working exe once our of 10 builds... Go figure... I upgraded to a different version of LabVIEW.

Have you tried mass compiling your project? I'd also try uninstalling the packages and reinstalling then after having cleared compiled object cache, just in case.
Are you able to compile and run a simple example with just a broker and client?

**Comment by russellgsystems** [comment]
@francois-normandin Thanks for your quick response.  I did try a simple example and it worked fine, see attached. I enabled debugging but the problem is still there. I have not tried the mass compile yet or reinstall, but I will try that.  I did try clearing compile cache.
[Build Error.zip](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/5642544/Build.Error.zip)

**Comment by francois-normandin** [comment]
One more thing I'd had to your potential list of fixes: reset the class mutation history of the modules that call the MQTT methods... Especially those you were using before the upgrade to 3.1.x.
My thinking is that some of the classes have been moved to different namespace on the process. Your classes might have issues handling the mutation when compiled. Clearing the mutation history can be done in a text editor or by renaming a class. I don't know if lvlib are affected by that too. I guess not since they don't have private data...

**Comment by russellgsystems** [comment]
How do you reset the class mutation history?  Do you have link that says how to do it?

**Comment by francois-normandin** [comment]
I just opened the PC... (was answering from my phone). Gimme a minute and I'll get you something.

**Comment by francois-normandin** [comment]
1. Probably the simplest way: 
From LAVAG (https://lavag.org/topic/14011-remove-history-from-lvclass)

> FYI, Aristos Queue mentioned that renaming a class or moving it into and out of a library will remove its mutation history, since at that point it's considered a different class.

The caveat is that your project, if large, will churn a lot to recompile everything. If you have multiple classes with many dependencies, it could take a while...

2. There now seems to be a method in vilib to do it: 
https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000015BLnSAM&l=en-CA

Never used it. Just found out about it, and probably fairly recent (LabVIEW 2013 didn't have this available, I'm 90% certain)

3. And finally, my "old" preferred method is a little more "dangerous" but fast... and since you are using SCC, it's no big deal, really.
You open the lvclass in a text editor and you delete the whole XML section about mutation history "called NI.LVClass.Geneology"

For example: 
![image](https://user-images.githubusercontent.com/11728548/101164109-a8842880-3602-11eb-9b66-42fd4d677e40.png)

**Comment by francois-normandin** [comment]
@russellgsystems I was able to build your test app in LV2020.
I don't have 2019SP1 installed on this machine.
![image](https://user-images.githubusercontent.com/11728548/101165338-7c69a700-3604-11eb-8fae-763f8d5ea262.png)

**Comment by russellgsystems** [comment]
Thanks that example builds ok, but my application doesn't. I tried to mass compile but it didn't work.  I will uninstall all of the MQTT and then try again. If that doesn't work I will try the remove history.

**Comment by francois-normandin** [comment]
That's really a bummer.
I hope it turns out well. I'm currently deploying the broker and clients on an sbRIO-9627 with LV2020 and it also works nicely.
Honestly, I thought LV2019 was cured of those 2208 errors at runtime.

**Comment by francois-normandin** [comment]
You know, inspecting more closely your initial error report, this line strikes me as significant: 

![image](https://user-images.githubusercontent.com/11728548/101166192-e171cc80-3605-11eb-9b7a-815d15acf49b.png)

It tells me that the Control Packet class is missing its private data cluster at runtime, or if it's there, all the callers think it is somewhere else...

**Comment by russellgsystems** [comment]
I tried open my class outside of the project and it had a bunch of linking issues.  Several of the files were still linking here:
![image](https://user-images.githubusercontent.com/68344965/101173559-55ad6f80-3608-11eb-8932-12a8cd44a87d.png)

Could that be the problem?

**Comment by francois-normandin** [comment]
All the MQTT Packages are located under that folder, so it seems fine to me.
Here is a snapshot of my installation, if you'd like to compare with what you've got.

![image](https://user-images.githubusercontent.com/11728548/101175551-497adf80-3613-11eb-9f93-7d6b9c90065d.png)

**Comment by francois-normandin** [comment]
oh wait... under addons... The only things under addons are supposed to be menu files for the palettes

**Comment by russellgsystems** [comment]
You are right that is all under that folder, but some of the VIs were defaulting that folder when looking for VI on disk

**Comment by francois-normandin** [comment]
Ok, that must be from that migration issue that was reported in #158 .
Sorry that you'll need to repair your project manually.

**Comment by russellgsystems** [comment]
With the uninstall and relinking I have now got a bigger problem that some of the JKI openG VIs that the MQTT library depends on are now saved in version LV 2020 and I am getting an error when I try to open my project in LV 2019.  Trying to figure out how to unlink them and get it work on LV 2019 now.  Thanks again for all you help.

**Comment by francois-normandin** [comment]
What?
Can you give me the list of versions for the MQTT broker, client and packet?

I was unaware that the MQTT depended on OpenG packages.

**Comment by russellgsystems** [comment]
I am sorry I mistyped. It isn't OpenG it is actually JKI JSON Serialization. Here are some screenshots of the errors I am getting and the VI package manager.
![image](https://user-images.githubusercontent.com/68344965/101182792-3288bd00-3614-11eb-9bc8-04e64c0191fa.png)

![image](https://user-images.githubusercontent.com/68344965/101182642-f81f2000-3613-11eb-9c86-175b7852ee34.png)
![image](https://user-images.githubusercontent.com/68344965/101182826-3e747f00-3614-11eb-947b-990f2dd3befb.png)

![image](https://user-images.githubusercontent.com/68344965/101182869-4d5b3180-3614-11eb-8093-6fa40473e0ea.png)

**Comment by francois-normandin** [comment]
From what I can see, only the "OpenSerializer.JKI JSON" depends on OpenG packages, but those are installed by the JKI JSON Serializer package, so it is a dependency of a dependency (assuming you are using OpenSerializer JSON...

**Comment by francois-normandin** [comment]
I'm installing your configuration in LV2013. If there is a version problem, it should be obvious where it comes from.

**Comment by russellgsystems** [comment]
I think the problem is that I had a few of the LabVIEW Open Source Projects files in LV 2020.  I also didn't delete everything from the LabVIEW Open Source Project in LV 2019 either. I am reinstalling everything now in LV 2019 only.

**Comment by francois-normandin** [comment]
I cannot reproduce the LV2020 linkage.

**Comment by russellgsystems** [comment]
I think the issue right now seems to be with the OpenSerializer JKI JSON that I am using unrelated to the MQTT. I am uninstalling everything and reinstalling trying it again.

**Comment by russellgsystems** [comment]
@francois-normandin all of my linking issues are now resolved in the development environment, but I am still getting the error with the executable that I originally reported above.  The only think I haven't tried yet from your list of things to try above is to reset the class mutation history of the modules.  Do you still think I should try that?

**Comment by francois-normandin** [comment]
Mutation history only affects the ability to unflatten from previous object private data, so if you don't use this type of communication where you send the flattened object over a stream, I'd say you don't lose much in the process anyhow.
It would definitely be my next step.

If that does not work, I would try to replace the Control Packet class constants that are listed as missing the .ctl file in your first original post.

**Comment by russellgsystems** [comment]
I used the easy method to reset the class mutation, but the problem is still there. I also tried replacing the control but I got the same error. Any other things to try?

**Comment by francois-normandin** [comment]
@russellgsystems I'm afraid at this point there is not much left...
-Can you disable chunks of software until it runs? Even though your app won't be functional, that might segregate the issue a bit, and provide a path to repair.
-Can you see if it builds on LV2020?
-Can you get a colleague to see if it builds on his machine?

Other than piecemeal replacement of corrupted VIs, my next step would be to open a service request with NI. If I had not just deployed a broker in LabVIEW 2019 SP1, last week, I'd question the broker, but this is definitely working.

**Comment by russellgsystems** [comment]
Thanks @francois-normandin I really appreciate all your help today. I guess I will try those things.  The things that really gets me about this issue is that it was working a couple weeks ago after I upgraded to the new version of the MQTT. I am not really sure what changed.  It just all of sudden didn't work anymore.

**Comment by francois-normandin** [comment]
Good luck mate.

**Comment by russellgsystems** [comment]
This KB fixed my problem, but it caused all of the files to be saved with the executable, which is not ideal for deployment. Is it possible to shorten the names of some of the files to avoid this error? 

https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000019LboSAE&l=en-US

I got this error when trying to build it:

![image](https://user-images.githubusercontent.com/68344965/101233830-57b31500-3680-11eb-80aa-d6a6c66e3d03.png)

This what my build folder looks like now with all of the supporting files:

![image](https://user-images.githubusercontent.com/68344965/101233856-8335ff80-3680-11eb-9858-b4f77f861803.png)

**Comment by francois-normandin** [comment]
The infamous 255 characters limit... 
Since about 2012, I've always built all my EXEs in C:/builds and I've never hit this limitation, including with MQTT.

I cannot change the namespacing (lvlib:lvclass) nor can I change the name of any methods that are not private, so I doubt it would help.

If you change your build path to a shorter one (ex: C:/builds), it should fit in the exe. I don't think you need the 8.x layout scheme as mentioned in this article, nor having all the files out of the exe. I confirmed this with a recent build of mine.
However, if that's the case for your app, there are still a few avenues you can explore:

1. In the build spec, you can force a renaming for the few libraries that are problematic for the char length. 
2. You could package the MQTT libraries in packet project libraries and call them from your main exe. That way, you still retain the same open source code base but need and extra intermediary build step to use it in your app.
3. The last resort is to fork the source project and perform a complete refactoring of the namespace so that it is short enough for your project. The obvious caveat of this method is that it will be difficult to update your fork to follow future updates of the project.

I think the KB gives you a nice overview of all the possible changes to make so that it builds, and you can try a subset of those proposals to find one that does not require that all three dependencies are external to your app. I'd definitely explore options 1 and 2, preferentially same in that order.

**Comment by russellgsystems** [comment]
I just changed my build path and it fixed it. Thanks for your help!
