### ISSUE TITLE
TLS (formally known as SSL) Support

### ISSUE THREAD

**Issue by russellgsystems** [LabVIEW-Open-Source/LV-MQTT-Broker#168]
Hello @francois-normandin,

Are connections to the MQTT broker with TLS (formally known as SSL) supported?

Russell

**Comment by francois-normandin** [comment]
Hi @russellgsystems.
yes they are, provided you are in LV2020 and use the TLS Connection class.

At the moment, the connection class only authenticates the server. If you want client authentication as well, you'll need to override the TCP Connection class and implement the client auth in a similar way.

Look at this repository for the source code of Secured TCP Connection:
https://github.com/LabVIEW-Open-Source/MQTT-Connection-SecuredTCP

It is installable through VIPM.

There is also a Youtube video where I go through the whole process of generating self-signed certificates (server-side only)
https://www.youtube.com/watch?v=2-OJ-U6eTmE

**Comment by russellgsystems** [comment]
Thanks @francois-normandin,

This what I needed. First we are testing it without TSL but our MQTT broker has authentication, similar to the -u and -P described here: https://mosquitto.org/man/mosquitto_pub-1.html

How do we add this type of authentication to the TCP connect?

Russell

**Comment by francois-normandin** [comment]
I think the -u and -P are simply the "CONNECT" packet's payload and can be set as an argument in the payload cluster.
![image](https://user-images.githubusercontent.com/11728548/129232102-ca1fc656-592d-429e-b085-2d74e9d29074.png)

For the TLS, mosquitto supports X509 certificates. That's the one that is supported by LabVIEW 2020.

**Comment by francois-normandin** [comment]
The MQTT Client is a full-fledged client. What I meant by that statement is that my goal was to produce a broker, but because of complete symmetry between the broker and client, the client was obtained for free, simply by refactoring the hierarchy with a common base class.
To my knowledge, the client is 100% compliant with MQTT 3.1.1 specs. The broker still lacks a few bells and whistles.
The LabVIEW open Source Project MQTT Client is split from the broker and put in this repo: 
https://github.com/LabVIEW-Open-Source/MQTT-Client

There are other clients out there. Here are a few from Github: 
https://github.com/search?q=labview+mqtt

**Comment by russellgsystems** [comment]
Hello @francois-normandin,

That is what I thought. Thanks for the clarification. About the user name and password I think you are right that they are part of the connect based on this link https://www.hivemq.com/blog/mqtt-security-fundamentals-authentication-username-password/, but I don't know how to add them to the connection or payload for this LV library. I don't think the -u and -P are supported because they are specific to the mosquitto app.  Any thoughts on how this might work? I am trying to test it out topic for the subscribe with this username and password, but I am unable to connect to the server right now from the LV client. I am getting an error 66.

Thanks

**Comment by francois-normandin** [comment]
It seems the document refers instead to the Connect flags: 
![image](https://user-images.githubusercontent.com/11728548/129256480-a874e4ac-b085-4505-bb5a-de67c4bfdc67.png)
For the rest of the mosquitto-specific implementation, I'm not sure what this means.

**Comment by francois-normandin** [comment]
you will need to check both checkboxes in the Connect Flags AND write the username/password in the Connect payload.

**Comment by francois-normandin** [comment]
if you need to debug the connection, my advice would be to use the Connection.SecuredTCP class "barebone" and create a Connect packet manually. You can then wait for the Connack packet as a response.

Take the example code in the MQTT Control Packets palette and adjust it to use only the Client loop at the bottom.
When you do that, you can create only a packet on-demand. By doing that, you can simplify the whole client process to just a "Write CONNECT" and "Wait for CONNACK".
![image](https://user-images.githubusercontent.com/11728548/129257406-c127ca8c-cbdd-4b8c-b626-481dcead314a.png)

**Comment by francois-normandin** [comment]
Ultimately, it boils down to this simple example, where you replace the client's Write with the bytes that form a Connect packet. The server will reply with Connack in the following node.

![image](https://user-images.githubusercontent.com/11728548/129257490-c59a38c7-5355-49d3-b7da-67ece26b4376.png)

**Comment by francois-normandin** [comment]
@russellgsystems  Great news. 

I was just about to upload this, so for anyone else wondering, here is the simple example I was talking about.

This is an example that returns Error 66 if you set the username and/or password to be empty strings.
Otherwise, the "local server" should return "Bad username or password". Disable the "local server" for testing remote.

[Example_LV2020_SecuredTCP.zip](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/files/6978374/Example_LV2020_SecuredTCP.zip)
