### ISSUE TITLE
How many clients can I access to the broker?

### ISSUE THREAD

**Issue by fatherJun** [LabVIEW-Open-Source/LV-MQTT-Broker#180]
Thank you always for your hard work.

**Comment by francois-normandin** [comment]
The connection handler creates a new session for each new connection, so it would be limited by the number of concurrent processes LabVIEW can handle. You're likely going to see performance degradation before you hit any software limits.

You could have a thousand clients that simply publish data in bursts, and a single clients subscribing to all incoming packets, and it might still give you better performance than ten clients that subscribe to all messages while publishing continuously at higher rate. It will really depend on the topology of your nodes and how much use of the Subscribe packet you do.

Each connection session (one per client) also generates one subscription session per topic it subscribes to. When a message is published, the subscription sessions are doing all the work to decide if the packet matches the topic filter. Connection sessions will handle the redirection to your client only on match. In this sense, the limitation in number of clients is related to the number of subscriptions, modulated by the frequency of the messages.

I'm sorry to give a complex answer instead of a simple number. Unfortunately you'll hit throughput limitations before connection limitations.

**Comment by francois-normandin** [comment]
I guess a limitation will be the number of ports on the subnet your broker serves. I'll say 65535 as a hard limit for 255.255.255.0 subnet mask.
