### ISSUE TITLE
Sending data to AWS IoT Core

### ISSUE THREAD

**Issue by MiguelMar98** [LabVIEW-Open-Source/LV-MQTT-Broker#183]
Hello, 

I followed the guide on how to connect to IoT Core through LabVIEW and now I can send message to my thing's shadow. Connection is good. I have some questions regarding how to format the data being published. 

I'm monitoring my test topic with the test client on IoT Core and I can see my data but there is this formatting issue..

![Test Client Format](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/166087050/c97ccea9-f4b9-4902-9fed-02ed7cedf410)

This is how the message is being displayed if I publish directly from the test client:

![Test Client Format OK](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/166087050/918c6086-543a-461f-a550-53761a66a548)

I've tried sending the data straight from a string constant, integer constant, variant data type but with all of those I'm getting the same result. 

This is my block diagram, I know that IoT Core sends data on a JSON format, is that the issue with the formatting problem?

![Block Diagram](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/166087050/750b62ec-2e7f-4759-8bc7-e89e1446c374)

Thank you

**Comment by MiguelMar98** [comment]
Oh SORRY I just realised this is meant to be on the Clietn Page not the broker

**Comment by francois-normandin** [comment]
@MiguelMar98 

The method you use to Publish your data is serializing the variant as a flattened LabVIEW string... this is the reason why you see a few funny characters.
Here, you have two choices. Either you define a serializer (JSON in this case) or you use the Publish Raw method to send bytes that you have serialized beforehand.

In this video, around the 12th minute, I demonstrate how to change your serializer.
Around the 14th minute, this is where I select a different default serializer.
https://www.youtube.com/watch?v=Y-jrwyfD9DU

![image](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/11728548/bcded3c6-faa0-4284-b577-e40a89ef8c70)

Alternatively, instead of publishing with the Variant payload, use this method instead: 
![image](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/11728548/f17d0207-b716-4bbd-b208-15bb5cf2cf05)

All-in-all, you can use any of these methodologies:

![image](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/11728548/27c33060-a5a8-4ffa-a198-5fdf15b7943a)

**Comment by francois-normandin** [comment]
This is the serializer you probably want.
https://www.vipm.io/package/labview_open_source_project_lib_serializer_jki_json/

**Comment by MiguelMar98** [comment]
Thank you again! Using the serializer worked. 
![image](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/166087050/7a9a88a1-a832-410a-8527-84641d8b022e)

![image](https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/assets/166087050/0290df55-7c79-43e3-9004-bdda65c4b260)
